### ISSUE TITLE
issue #21 fix submit add property to db

### ISSUE THREAD

**Issue by kngcr** [house-finders/house-finders#26]

**Comment by mlee-uhm** [comment]
I expect that this issue will take about half an hour to complete, since it just involves comparing the addProperty file from this repository with the addContact file in digits and finding what's different.

**Comment by domalian** [comment]
I spent almost a 2 hours trying to get the "Add properties" button to show only for landlords. It now works! I had to update the authOptions.ts so that a session callback actually returns the subrole property as well. Spent about an hour analyzing the code and looking for the file that was impacting this, and another hour fixing the code.  I also changed the defaultAccounts to keep it simple. I think it got too convoluted

**Comment by kngcr** [comment]
@domalian and I had realized that a required `id` was an issue, and commenting out line 27 of validationSchemas.ts fixed the problem of not properly seeding the database with default properties. Our form did not require an `id` to be set upon adding a property but our code was expecting it. This also brought our attention to properties needing to be unique, so that was changed as well in the same .ts file. Overall, this process took 2 hours. An hour was spent on looking over the code twice by the two of us independently.
